Add id card number birth date validator
cermati/satpam pull request #43
Opened 2017-07-10 08:22 UTC by sendyhalim

2017-07-10 08:39 UTC, febrianyuwono commented on test/validators/indonesia-id-card-number-birth-date.spec.js
> +  it('should success when given invalid id card that does not match birth date', () => {
should not success / should fail

2017-07-10 08:49 UTC, febrianyuwono requested changes

2017-07-10 08:49 UTC, febrianyuwono commented on test/validators/indonesia-id-card-number-birth-date.spec.js
> +  it('should success when given invalid id card that does not match birth date', () => {
should not success / should fail

2017-07-10 08:49 UTC, febrianyuwono commented on src/validators/indonesia-id-card-number-birth-date.js
> +  const birthDateValue = moment(inputObj[birthDateInputKey], birthDateInputFormat).format('DDMMYYYY');
ini bukannya harusnya DDMMYY ya?

2017-07-10 08:49 UTC, febrianyuwono commented on test/validators/indonesia-id-card-number-birth-date.spec.js
> +      birthDate: '02-09-93'
ini bukannya harusnya formatnya `DD-MM-YYYY`ya?

2017-07-10 08:49 UTC, febrianyuwono commented on test/validators/indonesia-id-card-number-birth-date.spec.js
> +      birthDate: '02-10-93'
sama dengan di atas

2017-07-10 12:23 UTC, sendyhalim commented on test/validators/indonesia-id-card-number-birth-date.spec.js
> +  it('should success when given invalid id card that does not match birth date', () => {
Oh iya bener juga, makasih feb akan diperbaiki :whale:

2017-07-10 12:28 UTC, sendyhalim commented on src/validators/indonesia-id-card-number-birth-date.js
> +  const birthDateValue = moment(inputObj[birthDateInputKey], birthDateInputFormat).format('DDMMYYYY');
Betul saya salah, plus test case nya jg ad yg salah haha

2017-07-11 07:40 UTC, febrianyuwono approved these changes

2017-07-11 07:44 UTC, merged