Add digit validation rule
cermati/satpam pull request #79
Opened 2018-11-30 11:59 UTC by stvyang

2018-11-30 16:45 UTC, sendyhalim requested changes

2018-11-30 16:45 UTC, sendyhalim commented on src/validators/digit.js
> +  if (isEmpty(val)){
Be careful 
```
_.isEmpty(0) -> true
_.isEmpty(1) -> true
```
Probably better to move the logic to cast the number to string before this if clause

```
const strValue = String(val);

if (isEmpty(val)) {
  return false;
}

const regexp = /^\d*$/g;

return regexp.test(strVal);
```

2018-11-30 16:45 UTC, sendyhalim commented on src/validators/digit.js
> +  const regexp = /^\d*$/g;
You should move this outside the function so the regexp instance won't be created per function call

2018-12-03 08:11 UTC, albertstevelino approved these changes
I'm ok with this

2018-12-03 08:27 UTC, merged